<?php
	/**
	 * bodyFooter.inc
	 * Contains the footer for each THINKer page
	 *
	 * @author Cory Gehr
	 */
?>
      </div>
      <!--END WORKING BODY-->

      <!--BEGIN FOOTER-->

      <footer class="footer">
        <p>
          Copyright &copy; <script>document.write(new Date().getFullYear())</script> Penn State University Emergency Management<br>
          Site Designed by IST 440W Team 21 Spring 2015<br>
          Chris Grega, Cory Gehr, Emily Moore, Taylor Dreitlein</p>
      </footer>
      <!--END FOOTER-->
    </div>
    <!--END CONTAINER-->
    
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="html/psueoc/js/bootstrap.min.js"></script>