<?php
	/**
	 * bodyFooter.inc
	 * Contains the footer for each THINKer page
	 *
	 * @author Cory Gehr
	 */
?>
      </div>
      <!--END WORKING BODY-->

      <!--BEGIN FOOTER-->

      <footer class="footer">
        <p>Copyright &copy; 2015 Penn State University Emergency Management</p>
        <p>Site Designed by IST 440W Team 21 Spring 2015</p>
        <p>Chris Grega, Cory Gehr, Emily Moore, Taylor Dreitlein</p>
      </footer>
      <!--END FOOTER-->
    </div>
    <!--END CONTAINER-->
    

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="html/psueoc/js/bootstrap.min.js"></script>