<?php
	/**
	 * head.inc
	 * Contains the HTML Header for THINKer
	 *
	 * @author Cory Gehr
	 */

?>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Penn State Emergency Operations | Parking Management</title>

    <!-- Bootstrap core css -->
    <link href="html/psueoc/css/bootstrap.min.css" rel="stylesheet">
    <!--custom styles for this site-->
    <link href="html/psueoc/css/eoc.css" rel="stylesheet">
    <link href="html/psueoc/css/justified-nav.css" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->